services:
  postgres:
    image: postgres:14-alpine
    container_name: coldchain-postgres
    environment:
      POSTGRES_DB: coldchain_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
    container_name: coldchain-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=host.docker.internal  # สำหรับ Windows/Mac
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coldchain_db
    extra_hosts:
      - "host.docker.internal:host-gateway"