services:
  postgres:
    image: postgres:14-alpine
    container_name: coldchain-postgres
    environment:
      POSTGRES_DB: coldchain_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend:/app/backend

volumes:
  postgres-data: